######################################################################
# Automatically generated by qmake (3.0) pon. cze 15 19:55:57 2015
######################################################################

TEMPLATE = app
TARGET = browser
INCLUDEPATH += .

# Input
HEADERS += browser.hpp
SOURCES += browser.cpp main.cpp

QT += webkit webkitwidgets widgets
