######################################################################
# Automatically generated by qmake (2.01a) pon. sie 20 15:39:11 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += browser.hpp
SOURCES += browser.cpp main.cpp

# to use webkit engine
QT += webkit
